version: "3.9"

services:
  postgres:
    image: sweetkennny/custom-postgres:15
    container_name: postgres15
    environment:
      POSTGRES_USER: jinwoo
      POSTGRES_PASSWORD: arise
      POSTGRES_DB: ahjin
    ports:
      - "5432:5432"

  webapp:
    image: sweetkennny/dapp01-web:1.0
    container_name: dapp01-web
    ports:
      - "3000:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ahjin
      SPRING_DATASOURCE_USERNAME: jinwoo
      SPRING_DATASOURCE_PASSWORD: arise
